server:
  port: 8083

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:mysql://localhost:3311/analytics_db
    username: analytics_user
    password: analytics_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
